### ISSUE TITLE
Does this package work with Laravel 5?

### ISSUE THREAD

**Issue by amandasaffer** [cyberomulus/PodcastGenerator#1]

**Comment by cyberomulus** [comment]
Hello,

I don't test with Laravel.

But it is a library that does not use any specific dependency.
You simply create objects and fill as desired.

Personally I use it with Symfony and in à simple php application for my tests.
I extract my medias in Doctrine and create all Media Object.

In futur version, a interface for media will be created.
This method for easy coupling with the entities.

**Comment by cyberomulus** [comment]
Have you à feedback of your experience with Laravel ?
